version: "3.3"

services:
  postgresbusiness:
    image: postgres:latest
    environment:
      POSTGRES_DB: businessadmin
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5433:5433"
    volumes:
      - "~/postgres_databusiness:/var/lib/postgresql/databusiness"
  pgadminbusiness:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 5050:80